language: python
env:
  - DATABASE_URL=postgres://postgres@localhost/tusk
python:
  - 2.7
install: pip install -q --use-mirrors tox
before_script:
  - psql -c 'create database tusk;' -U postgres
script: tox
