language: python
env:
  - DATABASE_URL=postgres://postgres@localhost:5432/tusk
python:
  - 2.6
  - 2.7
  - 3.3
install: pip install -q tox
before_script:
  - psql -c 'create database tusk;' -U postgres
script: tox
